### ISSUE TITLE
Help me! sentencepiece_trainer.cc(77) LOG(INFO) Starts training with :)

### ISSUE THREAD

**Issue by Sauong** [LibreTranslate/Locomotive#15]
//Please help me solve this problem.//

PS D:\Train Model\Locomotive-main> python train.py --config model-config.json
Training English --> Italian (1.0)
Sources: 1
https://data.argosopentech.com/data-tildemodel-en_it.argosdata [100%]     
Extracting D:\Train Model\Locomotive-main\cache\b84558a9ab99fe23d7adc7f9cce7879c.zip to D:\Train Model\Locomotive-main\cache\b84558a9ab99fe23d7adc7f9cce7879c
 - https://data.argosopentech.com/data-tildemodel-en_it.argosdata (hash:b84558a)
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/master/resources_1.1.0.json: 122kB [00:00, ?B/s]    
2024-02-08 00:12:58 INFO: Downloading these customized packages for language: en (English)...
=======================
| Processor | Package |
-----------------------
| tokenize  | ewt     |
=======================

Downloading http://nlp.stanford.edu/software/stanza/1.1.0/en/tokenize/ewt.pt: 100%|██████████| 631k/631k [00:00<00:00, 709kB/s]
2024-02-08 00:13:01 INFO: Finished downloading models and saved to D:\Train Model\Locomotive-main\run\en_it-1.0\stanza.
No sources merged
sentencepiece_trainer.cc(77) LOG(INFO) Starts training with :
trainer_spec {
  input_format:
  model_prefix: D:\Train Model\Locomotive-main\run\en_it-1.0/sentencepiece
  model_type: UNIGRAM
  vocab_size: 50000
  self_test_sample_size: 0
  character_coverage: 1
  input_sentence_size: 1000000
  shuffle_input_sentence: 1
  seed_sentencepiece_size: 1000000
  shrinking_factor: 0.75
  max_sentence_length: 4192
  num_threads: 16
  num_sub_iterations: 2
  max_sentencepiece_length: 16
  split_by_unicode_script: 1
  split_by_number: 1
  split_by_whitespace: 1
  split_digits: 0
  pretokenization_delimiter:
  treat_whitespace_as_suffix: 0
  allow_whitespace_only_pieces: 0
  required_chars:
  byte_fallback: 0
  vocabulary_output_piece_score: 1
  train_extremely_large_corpus: 0
  hard_vocab_limit: 1
  use_all_vocab: 0
  unk_id: 0
  bos_id: 1
  eos_id: 2
  pad_id: -1
  unk_piece: <unk>
  bos_piece: <s>
  eos_piece: </s>
  pad_piece: <pad>
  unk_surface:  โ
  enable_differential_privacy: 0
  differential_privacy_noise_level: 0
  differential_privacy_clipping_threshold: 0
}
normalizer_spec {
  name: nmt_nfkc
  add_dummy_prefix: 1
  remove_extra_whitespaces: 1
  escape_whitespaces: 1
  normalization_rule_tsv:
}
denormalizer_spec {}
Internal: D:\a\sentencepiece\sentencepiece\src\trainer_interface.cc(332) [(sentence_iterator_ != nullptr && trainer_spec_.input().empty()) || (sentence_iterator_ == nullptr && !trainer_spec_.input().empty())] SentenceIterator and trainer_spec.input() must be exclusive.

**Comment by f1refa11** [comment]
Hello, how were you able to fix this problem? I currently also have this issue.
