### ISSUE TITLE
Settings support

### ISSUE THREAD

**Issue by rentalhost** [LibreTranslate/Locomotive#26]
Hello,

I'm trying to figure out how to set up **Locomotive** to learn translation from scratch using a concept I'd like to apply. Basically, instead of direct translation from _EN_ to _PT_, I want to send a specific JSON pattern like `[EN, ES]` -> `PT`. This means having two input languages in JSON format to produce an output in _PT_.

I managed to do this with the standard settings using a very small dataset. However, the result was always a bit confusing. I believe it lacked processing time and a larger dataset, but since I was just testing, I felt slightly satisfied.

I plan to expand the input parameters to about 1,000,000 well-curated and verified data points, using another intelligence (like GPT) for some of the verification, while I'll manually verify other parts.

An example response would be something like:

- `["Hello","Holla"]` -> `"Olá"`
- `["The person was very unique.","Ella era muy única."]` -> `"Ela é muito única."`
- `["I spoke to Axel.","Ella es increíble."]` -> `"Eu falei com a Axel."` (_a_, female)

The focus is for the translation to be based on _English_ but use _Spanish_ context to identify gender when _English_ alone isn't sufficient.

Finally, I'd like to understand how I could configure the parameters to achieve the best possible results. I intend to use an RTX 4090 for this.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.libretranslate.com? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
